---
title: "DataFest"
output: pdf_document
---

# Reading Data
```{r, echo = F, warning=FALSE}

library(tidyverse)
library(ggmap)
library(maps)
library(mapdata)
library(dplyr)
library(fiftystater)
library(mapproj)
library(ggplot2)


load("data.rda")
cali <- read.csv("cali.csv", stringsAsFactors = FALSE)

```


# State Map
```{r}

jobData <- data %>% filter(jobAgeDays==0) # group data by jobid's to take into account duplcates 



jobData1 <- jobData[!c(is.na(jobData$normTitleCategory)),] # remove na rows for our plot (normcategory) 


state.data <- jobData1 %>% group_by(stateProvince, normTitleCategory) %>% tally() %>% top_n(1,n) # freq of listings by state 


names <- unique(state.data[duplicated(state.data$stateProvince),]$stateProvince)


state.data[which(state.data$stateProvince %in% names),] #MP is not on map.

state.data <- state.data[!c(duplicated(state.data$stateProvince)),]




data("fifty_states")
map_data("state")


states <- c("alabama","alaska", "arizona","arkansas","california","colorado","connecticut","delaware","florida",
"georgia","hawaii", "idaho","illinois","indiana","iowa","kansas", "kentucky","louisiana",
"maine","maryland","massachusetts","michigan","minnesota","mississippi","missouri","montana","nebraska",
"nevada", "new hampshire","new jersey","new mexico","new york","north carolina", "north dakota","ohio","oklahoma",
"oregon", "pennsylvania","rhode island","south carolina", "south dakota","tennessee","texas","utah","vermont",
"virginia","washington","west virginia","wisconsin","wyoming")



state.data_mod <- state.data

state.data_mod <- state.data_mod[state.data_mod$stateProvince %in% state.abb,]

state.data_mod <- state.data_mod[,-3]



# map of most frequent job category listings per state; if you want get a job in any of these areas, go to these states; based on indeed data, employers are looking for jobs most frequently in these categories 

# map_id creates the aesthetic mapping to the state name column in your data

group.colors <- c(food="#3288bd",
                  management="#fdae61",
                  # mednurse="#e6f598",
                  mednurse="#66c2a5",
                  retail="slategray")

# group.colors <- c(food="#fee08b",
#                   management="#f46d43",
#                   mednurse="#bf812d",
#                   retail="#9970ab")

# group.colors2 <- c(admin = "#9e0142",
# childcare = "#d53e4f",
# customer = "#f46d43",
# driver = "#fdae61",
# food = "#fee08b",
# management = "#ffffbf",
# mednurse = "#66c2a5",
# phramacy = "#abdda4",
# retail = "#e6f598",
# science = "#3288bd",
# techsoftware = "#5e4fa2", 
# warehouse = "slategray")
                    
statemap <-  ggplot(state.data_mod, aes(map_id = states)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = normTitleCategory), map = fifty_states, color = "black") + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  scale_fill_manual(values=group.colors) + 
  #scale_fill_brewer(palette="BuPu") +
  labs(x = "", y = "") +
  guides(fill=guide_legend(title="Job Category: "))+
  theme(legend.position = "bottom", 
        legend.text=element_text(size=15),
        legend.title=element_text(size=17),
        panel.background = element_blank())

statemap

#ggsave( "stateplot.png",statemap)


#PuBu, PuBuGn, BuPu, Pastel1, Paired
head(state.data_mod,10)
head(states,10)
```

```{r}
# table of listings for top industries

sum(filter(state.data,state.data$normTitleCategory == "management"))

nrow(jobData[jobData$normTitleCategory == "management",])

manage <- state.data[state.data$normTitleCategory == "management",]
sumManage <- nrow(jobData[jobData$normTitleCategory == "management",])

med <- state.data[state.data$normTitleCategory == "mednurse",]
sumMed <- nrow(jobData[jobData$normTitleCategory == "mednurse",])

ret <- state.data[state.data$normTitleCategory == "retail",]
sumRet <- nrow(jobData[jobData$normTitleCategory == "retail",])

food <- state.data[state.data$normTitleCategory == "food",]
sumfood <- nrow(jobData[jobData$normTitleCategory == "food",])


x <- data.frame(c("Management","Mednurse","Retail","Food"),
                c(sumManage, sumMed, sumRet, sumfood),
                c(sumManage/nrow(jobData), sumMed/nrow(jobData), sumRet/nrow(jobData), sumfood/nrow(jobData)))

colnames(x) <- c("Job Category","Total Number of Listings", "Percent")
x

# 406572 total number of listings 
```

# California Sub region map
```{r}
states <- map_data("state")
california <- subset(states, region %in% "california" )
counties <-  map_data("county")
ca_county <- subset(counties, region == "california")
  
cali <- cali[!c(is.na(cali$normTitleCategory)),] 
cali <- cali[!c(is.na(cali$county)),] 



cali2 <- cali %>% group_by(county, normTitleCategory) %>% tally() %>% top_n(1,n)


names <- unique(cali2[duplicated(cali2$county),]$county)


cali2[which(cali2$county %in% names),]

# hr/warehouse , install/insurance/medtech/retail/service/warehouse, management/mednurse, sanitation/warehouse , phrarmacy/project, food/mednurse, childcare/food/retail 

county.data <- cali2[!c(duplicated(cali2$county)),]



county.data<- as.matrix(county.data)

# county.data
# names

 county.data[6,2] <-  "warehouse"                 #"hr/warehouse"
 county.data[11,2] <- "retail"                    #"install/insurance/medtech/retail/service/warehouse"
 county.data[34,2] <- "management"                #"management/mednurse"
 county.data[51,2] <- "warehouse"                 #"sanitation/warehouse"
 county.data[52,2] <- "pharmacy"                 #"phrarmacy/project"
 county.data[53,2] <- "mednurse"                  #"food/mednurse"
 county.data[54,2] <- "retail"                    #"childcare/food/retail"



county.data <- as.data.frame(county.data)
colnames(county.data)[1] <- "subregion"

ca_county <- left_join(ca_county, county.data, by = "subregion" )

group.colors2 <- c(admin="#d73027",
                   childcare="#fdae61",
                   customer="#ffffbf",
                   driver="#fee090",
                   food="#a50026",
                   management="#f46d43",
                   mednurse="#bf812d",
                   phramacy="#abd9e9",
                   retail="#9970ab", 
                   science = "#74add1",
                   techsoftware = "#4575b4",
                   warehouse = "#313695")


group.colors2 <- c(admin = "#9e0142",
childcare = "#d53e4f",
customer = "#f46d43",
driver = "#fdae61",
food = "#fee08b",
management = "#ffffbf",
mednurse = "#66c2a5",
phramacy = "#abdda4",
retail = "#e6f598",
science = "#3288bd",
techsoftware = "#5e4fa2", 
warehouse = "slategray")

plot2 <- ggplot(data = ca_county) + 
  geom_polygon(aes(x = long, y = lat, fill = normTitleCategory ,  group = group), color = "black") + 
  coord_fixed(1.3)+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  guides(fill=guide_legend(title="Job Category"))+
  scale_fill_brewer(palette=c("Set3")) + 
  #scale_fill_manual(values=group.colors2) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank())
 

plot2
ggsave( "plot.png",plot2)
```

```{r}
clickData <- data %>% filter(jobAgeDays==0)

tallyClicks <- clickData %>% group_by(stateProvince) %>%  tally(clicks) 
tallYLOCClicks <- clickData %>% group_by(stateProvince) %>%  tally(localClicks) 


clickData <- as.data.frame(cbind( tallyClicks, Por = tallYLOCClicks$n/tallyClicks$n))

clickData <- clickData[which(clickData$stateProvince %in% state.abb),] #MP is not on map.


# Change state abbreviation to lower case full name
clickData$stateName <- tolower(state.name[match(clickData$stateProvince,state.abb)])

j <- ggplot(clickData, aes(map_id = stateName)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = Por), map = fifty_states, color = "black") + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "")+
  theme(legend.position = "bottom", 
        panel.background = element_blank())

j


```

```{r}


plot3 <- ggplot(data = ca_county) + 
  geom_polygon(aes(x = long, y = lat, fill = normTitleCategory ,  group = group), color = "black") + 
  coord_fixed(1.3)+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+ 
  guides(fill=guide_legend(title="Job Category"))+
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank())
 
plot3


head(ca_county)
head(county.data)
```









